/*
  LearnUp demo data for Microsoft SQL Server.
  Safe to run repeatedly: every insert checks a stable business key first.
  Demo password for all seeded accounts: 123456
*/

-- USERS
IF NOT EXISTS (SELECT 1 FROM users WHERE email = 'admin@gmail.com') INSERT INTO users (name,email,password,role,status,phone,occupation,country,province) VALUES (N'Quản Trị Viên','admin@gmail.com','$2a$10$2gYfQrr6anokDjvVCN6A7uSOln5uDP41pyrUqLI6Kk/QJJb9MRoU2',N'admin',N'active','0901234567',N'Quản trị hệ thống',N'Việt Nam',N'TP. Hồ Chí Minh');
IF NOT EXISTS (SELECT 1 FROM users WHERE email = 'teacher@gmail.com') INSERT INTO users (name,email,password,role,status,phone,occupation,country,province) VALUES (N'ThS. Nguyễn Văn Hùng','teacher@gmail.com','$2a$10$2gYfQrr6anokDjvVCN6A7uSOln5uDP41pyrUqLI6Kk/QJJb9MRoU2',N'teacher',N'active','0912345678',N'Giảng viên Tiếng Anh',N'Việt Nam',N'Hà Nội');
IF NOT EXISTS (SELECT 1 FROM users WHERE email = 'teacher2@gmail.com') INSERT INTO users (name,email,password,role,status,phone,occupation,country,province) VALUES (N'Cô Lê Thị Mai (IELTS 8.5)','teacher2@gmail.com','$2a$10$2gYfQrr6anokDjvVCN6A7uSOln5uDP41pyrUqLI6Kk/QJJb9MRoU2',N'teacher',N'active','0923456789',N'Chuyên gia Luyện thi IELTS',N'Việt Nam',N'Đà Nẵng');
IF NOT EXISTS (SELECT 1 FROM users WHERE email = 'teacher3@gmail.com') INSERT INTO users (name,email,password,role,status,phone,occupation,country,province) VALUES (N'Thầy Trần Quốc Bảo','teacher3@gmail.com','$2a$10$2gYfQrr6anokDjvVCN6A7uSOln5uDP41pyrUqLI6Kk/QJJb9MRoU2',N'teacher',N'active','0924567890',N'Giảng viên TOEIC và Giao tiếp',N'Việt Nam',N'TP. Hồ Chí Minh');
IF NOT EXISTS (SELECT 1 FROM users WHERE email = 'student@gmail.com') INSERT INTO users (name,email,password,role,status,phone,occupation,country,province) VALUES (N'Lê Tuấn Anh','student@gmail.com','$2a$10$2gYfQrr6anokDjvVCN6A7uSOln5uDP41pyrUqLI6Kk/QJJb9MRoU2',N'student',N'active','0934567890',N'Sinh viên',N'Việt Nam',N'TP. Hồ Chí Minh');
IF NOT EXISTS (SELECT 1 FROM users WHERE email = 'student2@gmail.com') INSERT INTO users (name,email,password,role,status,phone,occupation,country,province) VALUES (N'Trần Minh Quang','student2@gmail.com','$2a$10$2gYfQrr6anokDjvVCN6A7uSOln5uDP41pyrUqLI6Kk/QJJb9MRoU2',N'student',N'active','0945678901',N'Kỹ sư phần mềm',N'Việt Nam',N'Hà Nội');
IF NOT EXISTS (SELECT 1 FROM users WHERE email = 'student3@gmail.com') INSERT INTO users (name,email,password,role,status,phone,occupation,country,province) VALUES (N'Hoàng Thị Thảo','student3@gmail.com','$2a$10$2gYfQrr6anokDjvVCN6A7uSOln5uDP41pyrUqLI6Kk/QJJb9MRoU2',N'student',N'active','0956789012',N'Nhân viên Marketing',N'Việt Nam',N'Hải Phòng');
IF NOT EXISTS (SELECT 1 FROM users WHERE email = 'student4@gmail.com') INSERT INTO users (name,email,password,role,status,phone,occupation,country,province) VALUES (N'Nguyễn Phương Linh','student4@gmail.com','$2a$10$2gYfQrr6anokDjvVCN6A7uSOln5uDP41pyrUqLI6Kk/QJJb9MRoU2',N'student',N'active','0967890123',N'Sinh viên Đại học',N'Việt Nam',N'Đà Nẵng');
IF NOT EXISTS (SELECT 1 FROM users WHERE email = 'student5@gmail.com') INSERT INTO users (name,email,password,role,status,phone,occupation,country,province) VALUES (N'Phạm Đức Duy','student5@gmail.com','$2a$10$2gYfQrr6anokDjvVCN6A7uSOln5uDP41pyrUqLI6Kk/QJJb9MRoU2',N'student',N'active','0978901234',N'Nhân viên Ngân hàng',N'Việt Nam',N'Cần Thơ');

-- CATEGORIES
IF NOT EXISTS (SELECT 1 FROM categories WHERE name=N'Tiếng Anh Giao Tiếp') INSERT INTO categories(name) VALUES(N'Tiếng Anh Giao Tiếp');
IF NOT EXISTS (SELECT 1 FROM categories WHERE name=N'Luyện thi IELTS') INSERT INTO categories(name) VALUES(N'Luyện thi IELTS');
IF NOT EXISTS (SELECT 1 FROM categories WHERE name=N'Luyện thi TOEIC') INSERT INTO categories(name) VALUES(N'Luyện thi TOEIC');
IF NOT EXISTS (SELECT 1 FROM categories WHERE name=N'Tiếng Anh Thương Mại & CNTT') INSERT INTO categories(name) VALUES(N'Tiếng Anh Thương Mại & CNTT');
IF NOT EXISTS (SELECT 1 FROM categories WHERE name=N'Ngữ Pháp & Từ Vựng Căn Bản') INSERT INTO categories(name) VALUES(N'Ngữ Pháp & Từ Vựng Căn Bản');

-- COURSES
IF NOT EXISTS (SELECT 1 FROM courses WHERE title=N'Tiếng Anh Giao Tiếp Thực Chiến Cho Người Đi Làm') INSERT INTO courses(title,description,price,status,teacher_id,category_id) SELECT N'Tiếng Anh Giao Tiếp Thực Chiến Cho Người Đi Làm',N'Chuẩn hóa phát âm, phản xạ giao tiếp trong môi trường công sở, viết email và đàm phán chuyên nghiệp.',499000,N'published',u.id,c.id FROM users u CROSS JOIN categories c WHERE u.email='teacher@gmail.com' AND c.name=N'Tiếng Anh Giao Tiếp';
IF NOT EXISTS (SELECT 1 FROM courses WHERE title=N'Chinh Phục IELTS 7.0+ Toàn Diện 4 Kỹ Năng') INSERT INTO courses(title,description,price,status,teacher_id,category_id) SELECT N'Chinh Phục IELTS 7.0+ Toàn Diện 4 Kỹ Năng',N'Lộ trình từ 5.5 lên 7.0+, tập trung Listening, Reading, Writing và Speaking.',890000,N'published',u.id,c.id FROM users u CROSS JOIN categories c WHERE u.email='teacher2@gmail.com' AND c.name=N'Luyện thi IELTS';
IF NOT EXISTS (SELECT 1 FROM courses WHERE title=N'Bứt Phá TOEIC 750+ Cấp Tốc Trong 30 Ngày') INSERT INTO courses(title,description,price,status,teacher_id,category_id) SELECT N'Bứt Phá TOEIC 750+ Cấp Tốc Trong 30 Ngày',N'Tổng hợp ngữ pháp, từ vựng và chiến thuật làm bài TOEIC theo định dạng mới.',350000,N'published',u.id,c.id FROM users u CROSS JOIN categories c WHERE u.email='teacher@gmail.com' AND c.name=N'Luyện thi TOEIC';
IF NOT EXISTS (SELECT 1 FROM courses WHERE title=N'Tiếng Anh Chuyên Ngành CNTT (IT English)') INSERT INTO courses(title,description,price,status,teacher_id,category_id) SELECT N'Tiếng Anh Chuyên Ngành CNTT (IT English)',N'Thuật ngữ IT, giao tiếp trong Daily Standup, Sprint Planning và đọc tài liệu kỹ thuật.',550000,N'published',u.id,c.id FROM users u CROSS JOIN categories c WHERE u.email='teacher3@gmail.com' AND c.name=N'Tiếng Anh Thương Mại & CNTT';
IF NOT EXISTS (SELECT 1 FROM courses WHERE title=N'Từ Vựng Siêu Tốc 3000 Từ Tiếng Anh Căn Bản') INSERT INTO courses(title,description,price,status,submitted_at,teacher_id,category_id) SELECT N'Từ Vựng Siêu Tốc 3000 Từ Tiếng Anh Căn Bản',N'Học từ vựng theo chủ đề, phục vụ giao tiếp hằng ngày.',199000,N'pending',DATEADD(day,-1,SYSDATETIME()),u.id,c.id FROM users u CROSS JOIN categories c WHERE u.email='teacher2@gmail.com' AND c.name=N'Ngữ Pháp & Từ Vựng Căn Bản';
IF NOT EXISTS (SELECT 1 FROM courses WHERE title=N'Ngữ Pháp Tiếng Anh Nền Tảng A-Z') INSERT INTO courses(title,description,price,status,teacher_id,category_id) SELECT N'Ngữ Pháp Tiếng Anh Nền Tảng A-Z',N'Hệ thống hóa ngữ pháp tiếng Anh từ cơ bản đến nâng cao.',299000,N'published',u.id,c.id FROM users u CROSS JOIN categories c WHERE u.email='teacher3@gmail.com' AND c.name=N'Ngữ Pháp & Từ Vựng Căn Bản';

-- CHAPTERS
IF NOT EXISTS (SELECT 1 FROM chapters ch JOIN courses c ON c.id=ch.course_id WHERE c.title=N'Tiếng Anh Giao Tiếp Thực Chiến Cho Người Đi Làm' AND ch.title=N'Chương 1: Phản xạ giao tiếp công sở căn bản') INSERT INTO chapters(title,order_index,course_id) SELECT N'Chương 1: Phản xạ giao tiếp công sở căn bản',1,id FROM courses WHERE title=N'Tiếng Anh Giao Tiếp Thực Chiến Cho Người Đi Làm';
IF NOT EXISTS (SELECT 1 FROM chapters ch JOIN courses c ON c.id=ch.course_id WHERE c.title=N'Tiếng Anh Giao Tiếp Thực Chiến Cho Người Đi Làm' AND ch.title=N'Chương 2: Họp nhóm & Thuyết trình') INSERT INTO chapters(title,order_index,course_id) SELECT N'Chương 2: Họp nhóm & Thuyết trình',2,id FROM courses WHERE title=N'Tiếng Anh Giao Tiếp Thực Chiến Cho Người Đi Làm';
IF NOT EXISTS (SELECT 1 FROM chapters ch JOIN courses c ON c.id=ch.course_id WHERE c.title=N'Chinh Phục IELTS 7.0+ Toàn Diện 4 Kỹ Năng' AND ch.title=N'Chương 1: Chiến thuật Listening & Reading') INSERT INTO chapters(title,order_index,course_id) SELECT N'Chương 1: Chiến thuật Listening & Reading',1,id FROM courses WHERE title=N'Chinh Phục IELTS 7.0+ Toàn Diện 4 Kỹ Năng';
IF NOT EXISTS (SELECT 1 FROM chapters ch JOIN courses c ON c.id=ch.course_id WHERE c.title=N'Chinh Phục IELTS 7.0+ Toàn Diện 4 Kỹ Năng' AND ch.title=N'Chương 2: Writing & Speaking') INSERT INTO chapters(title,order_index,course_id) SELECT N'Chương 2: Writing & Speaking',2,id FROM courses WHERE title=N'Chinh Phục IELTS 7.0+ Toàn Diện 4 Kỹ Năng';
IF NOT EXISTS (SELECT 1 FROM chapters ch JOIN courses c ON c.id=ch.course_id WHERE c.title=N'Bứt Phá TOEIC 750+ Cấp Tốc Trong 30 Ngày') INSERT INTO chapters(title,order_index,course_id) SELECT N'Chương 1: Trọng tâm Ngữ pháp TOEIC',1,id FROM courses WHERE title=N'Bứt Phá TOEIC 750+ Cấp Tốc Trong 30 Ngày';
IF NOT EXISTS (SELECT 1 FROM chapters ch JOIN courses c ON c.id=ch.course_id WHERE c.title=N'Tiếng Anh Chuyên Ngành CNTT (IT English)') INSERT INTO chapters(title,order_index,course_id) SELECT N'Chương 1: Giao tiếp Scrum/Agile',1,id FROM courses WHERE title=N'Tiếng Anh Chuyên Ngành CNTT (IT English)';
IF NOT EXISTS (SELECT 1 FROM chapters ch JOIN courses c ON c.id=ch.course_id WHERE c.title=N'Từ Vựng Siêu Tốc 3000 Từ Tiếng Anh Căn Bản') INSERT INTO chapters(title,order_index,course_id) SELECT N'Chương 1: Từ vựng đời sống',1,id FROM courses WHERE title=N'Từ Vựng Siêu Tốc 3000 Từ Tiếng Anh Căn Bản';
IF NOT EXISTS (SELECT 1 FROM chapters ch JOIN courses c ON c.id=ch.course_id WHERE c.title=N'Ngữ Pháp Tiếng Anh Nền Tảng A-Z') INSERT INTO chapters(title,order_index,course_id) SELECT N'Chương 1: Các thì cơ bản',1,id FROM courses WHERE title=N'Ngữ Pháp Tiếng Anh Nền Tảng A-Z';

-- LESSONS (title is used as the stable demo key)
IF NOT EXISTS (SELECT 1 FROM lessons WHERE title=N'Bài 1: Tự tin giới thiệu bản thân & công việc') INSERT INTO lessons(title,video_url,order_index,chapter_id) SELECT N'Bài 1: Tự tin giới thiệu bản thân & công việc','https://www.youtube.com/watch?v=juKd26qkNAw',1,id FROM chapters WHERE title=N'Chương 1: Phản xạ giao tiếp công sở căn bản';
IF NOT EXISTS (SELECT 1 FROM lessons WHERE title=N'Bài 2: Viết Email và tin nhắn công việc chuyên nghiệp') INSERT INTO lessons(title,video_url,order_index,chapter_id) SELECT N'Bài 2: Viết Email và tin nhắn công việc chuyên nghiệp','https://www.youtube.com/watch?v=juKd26qkNAw',2,id FROM chapters WHERE title=N'Chương 1: Phản xạ giao tiếp công sở căn bản';
IF NOT EXISTS (SELECT 1 FROM lessons WHERE title=N'Bài 3: Đặt lịch họp và xác nhận qua điện thoại') INSERT INTO lessons(title,video_url,order_index,chapter_id) SELECT N'Bài 3: Đặt lịch họp và xác nhận qua điện thoại','https://www.youtube.com/watch?v=juKd26qkNAw',3,id FROM chapters WHERE title=N'Chương 1: Phản xạ giao tiếp công sở căn bản';
IF NOT EXISTS (SELECT 1 FROM lessons WHERE title=N'Bài 4: Mẫu câu đưa ra ý kiến trong cuộc họp') INSERT INTO lessons(title,video_url,order_index,chapter_id) SELECT N'Bài 4: Mẫu câu đưa ra ý kiến trong cuộc họp','https://www.youtube.com/watch?v=juKd26qkNAw',1,id FROM chapters WHERE title=N'Chương 2: Họp nhóm & Thuyết trình';
IF NOT EXISTS (SELECT 1 FROM lessons WHERE title=N'Bài 5: Kỹ năng thuyết trình dự án bằng tiếng Anh') INSERT INTO lessons(title,video_url,order_index,chapter_id) SELECT N'Bài 5: Kỹ năng thuyết trình dự án bằng tiếng Anh','https://www.youtube.com/watch?v=juKd26qkNAw',2,id FROM chapters WHERE title=N'Chương 2: Họp nhóm & Thuyết trình';
IF NOT EXISTS (SELECT 1 FROM lessons WHERE title=N'Bài 1: Phương pháp xử lý Multiple Choice trong Listening') INSERT INTO lessons(title,video_url,order_index,chapter_id) SELECT N'Bài 1: Phương pháp xử lý Multiple Choice trong Listening','https://www.youtube.com/watch?v=juKd26qkNAw',1,id FROM chapters WHERE title=N'Chương 1: Chiến thuật Listening & Reading';
IF NOT EXISTS (SELECT 1 FROM lessons WHERE title=N'Bài 2: Chiến lược Skimming & Scanning trong Reading') INSERT INTO lessons(title,video_url,order_index,chapter_id) SELECT N'Bài 2: Chiến lược Skimming & Scanning trong Reading','https://www.youtube.com/watch?v=juKd26qkNAw',2,id FROM chapters WHERE title=N'Chương 1: Chiến thuật Listening & Reading';
IF NOT EXISTS (SELECT 1 FROM lessons WHERE title=N'Bài 3: Cấu trúc bài luận Writing Task 2') INSERT INTO lessons(title,video_url,order_index,chapter_id) SELECT N'Bài 3: Cấu trúc bài luận Writing Task 2','https://www.youtube.com/watch?v=juKd26qkNAw',1,id FROM chapters WHERE title=N'Chương 2: Writing & Speaking';
IF NOT EXISTS (SELECT 1 FROM lessons WHERE title=N'Bài 4: Bứt phá Speaking Part 2 và 3') INSERT INTO lessons(title,video_url,order_index,chapter_id) SELECT N'Bài 4: Bứt phá Speaking Part 2 và 3','https://www.youtube.com/watch?v=juKd26qkNAw',2,id FROM chapters WHERE title=N'Chương 2: Writing & Speaking';
IF NOT EXISTS (SELECT 1 FROM lessons WHERE title=N'Bài 1: Dạng câu hỏi về Từ loại') INSERT INTO lessons(title,video_url,order_index,chapter_id) SELECT N'Bài 1: Dạng câu hỏi về Từ loại','https://www.youtube.com/watch?v=juKd26qkNAw',1,id FROM chapters WHERE title=N'Chương 1: Trọng tâm Ngữ pháp TOEIC';
IF NOT EXISTS (SELECT 1 FROM lessons WHERE title=N'Bài 2: Bẫy Mệnh đề quan hệ') INSERT INTO lessons(title,video_url,order_index,chapter_id) SELECT N'Bài 2: Bẫy Mệnh đề quan hệ','https://www.youtube.com/watch?v=juKd26qkNAw',2,id FROM chapters WHERE title=N'Chương 1: Trọng tâm Ngữ pháp TOEIC';
IF NOT EXISTS (SELECT 1 FROM lessons WHERE title=N'Bài 1: Báo cáo tiến độ Daily Standup Meeting') INSERT INTO lessons(title,video_url,order_index,chapter_id) SELECT N'Bài 1: Báo cáo tiến độ Daily Standup Meeting','https://www.youtube.com/watch?v=juKd26qkNAw',1,id FROM chapters WHERE title=N'Chương 1: Giao tiếp Scrum/Agile';
IF NOT EXISTS (SELECT 1 FROM lessons WHERE title=N'Bài 2: Đọc hiểu API Specs & Git Workflow') INSERT INTO lessons(title,video_url,order_index,chapter_id) SELECT N'Bài 2: Đọc hiểu API Specs & Git Workflow','https://www.youtube.com/watch?v=juKd26qkNAw',2,id FROM chapters WHERE title=N'Chương 1: Giao tiếp Scrum/Agile';
IF NOT EXISTS (SELECT 1 FROM lessons WHERE title=N'Bài 1: Từ vựng gia đình') INSERT INTO lessons(title,video_url,order_index,chapter_id) SELECT N'Bài 1: Từ vựng gia đình','https://www.youtube.com/watch?v=juKd26qkNAw',1,id FROM chapters WHERE title=N'Chương 1: Từ vựng đời sống';
IF NOT EXISTS (SELECT 1 FROM lessons WHERE title=N'Bài 1: Hiện tại đơn & Tiếp diễn') INSERT INTO lessons(title,video_url,order_index,chapter_id) SELECT N'Bài 1: Hiện tại đơn & Tiếp diễn','https://www.youtube.com/watch?v=juKd26qkNAw',1,id FROM chapters WHERE title=N'Chương 1: Các thì cơ bản';
IF NOT EXISTS (SELECT 1 FROM lessons WHERE title=N'Bài 2: Quá khứ đơn & Hoàn thành') INSERT INTO lessons(title,video_url,order_index,chapter_id) SELECT N'Bài 2: Quá khứ đơn & Hoàn thành','https://www.youtube.com/watch?v=juKd26qkNAw',2,id FROM chapters WHERE title=N'Chương 1: Các thì cơ bản';

-- QUIZZES
IF NOT EXISTS (SELECT 1 FROM quizzes WHERE title=N'Kiểm tra Đánh giá Giao tiếp Công sở (Quiz 1)') INSERT INTO quizzes(title,pass_score,time_limit_minutes,course_id) SELECT N'Kiểm tra Đánh giá Giao tiếp Công sở (Quiz 1)',80,15,id FROM courses WHERE title=N'Tiếng Anh Giao Tiếp Thực Chiến Cho Người Đi Làm';
IF NOT EXISTS (SELECT 1 FROM quizzes WHERE title=N'IELTS Diagnostic Assessment (Band 7.0 Test)') INSERT INTO quizzes(title,pass_score,time_limit_minutes,course_id) SELECT N'IELTS Diagnostic Assessment (Band 7.0 Test)',75,20,id FROM courses WHERE title=N'Chinh Phục IELTS 7.0+ Toàn Diện 4 Kỹ Năng';
IF NOT EXISTS (SELECT 1 FROM quizzes WHERE title=N'TOEIC Mini Mock Test (Part 5 Focus)') INSERT INTO quizzes(title,pass_score,time_limit_minutes,course_id) SELECT N'TOEIC Mini Mock Test (Part 5 Focus)',70,10,id FROM courses WHERE title=N'Bứt Phá TOEIC 750+ Cấp Tốc Trong 30 Ngày';

-- QUESTIONS
IF NOT EXISTS (SELECT 1 FROM questions WHERE content=N'Mẫu câu nào sau đây phù hợp nhất để mở đầu một email trang trọng gửi đối tác?') INSERT INTO questions(quiz_id,content,explanation,order_index) SELECT id,N'Mẫu câu nào sau đây phù hợp nhất để mở đầu một email trang trọng gửi đối tác?',N'“Dear Mr. Smith, I hope this email finds you well.” là cách mở đầu trang trọng và phù hợp.',1 FROM quizzes WHERE title=N'Kiểm tra Đánh giá Giao tiếp Công sở (Quiz 1)';
IF NOT EXISTS (SELECT 1 FROM questions WHERE content=N'Khi muốn xin phép ngắt lời ai đó một cách lịch sự trong cuộc họp, bạn nên nói gì?') INSERT INTO questions(quiz_id,content,explanation,order_index) SELECT id,N'Khi muốn xin phép ngắt lời ai đó một cách lịch sự trong cuộc họp, bạn nên nói gì?',N'“May I interrupt for a moment?” là cách ngắt lời lịch thiệp.',2 FROM quizzes WHERE title=N'Kiểm tra Đánh giá Giao tiếp Công sở (Quiz 1)';
IF NOT EXISTS (SELECT 1 FROM questions WHERE content=N'Từ nào đồng nghĩa với "Postpone a meeting"?') INSERT INTO questions(quiz_id,content,explanation,order_index) SELECT id,N'Từ nào đồng nghĩa với "Postpone a meeting"?',N'“Postpone” và “Put off” đều có nghĩa là hoãn lại.',3 FROM quizzes WHERE title=N'Kiểm tra Đánh giá Giao tiếp Công sở (Quiz 1)';
IF NOT EXISTS (SELECT 1 FROM questions WHERE content=N'Trong IELTS Reading, kỹ thuật "Scanning" dùng để làm gì?') INSERT INTO questions(quiz_id,content,explanation,order_index) SELECT id,N'Trong IELTS Reading, kỹ thuật "Scanning" dùng để làm gì?',N'Scanning dùng để tìm nhanh thông tin cụ thể như tên riêng, số liệu và từ khóa.',1 FROM quizzes WHERE title=N'IELTS Diagnostic Assessment (Band 7.0 Test)';
IF NOT EXISTS (SELECT 1 FROM questions WHERE content=N'Một bài Writing Task 2 tiêu chuẩn nên có tối thiểu bao nhiêu từ?') INSERT INTO questions(quiz_id,content,explanation,order_index) SELECT id,N'Một bài Writing Task 2 tiêu chuẩn nên có tối thiểu bao nhiêu từ?',N'IELTS Writing Task 2 yêu cầu tối thiểu 250 từ.',2 FROM quizzes WHERE title=N'IELTS Diagnostic Assessment (Band 7.0 Test)';
IF NOT EXISTS (SELECT 1 FROM questions WHERE content=N'The manager asked all staff members to submit ______ reports by Friday.') INSERT INTO questions(quiz_id,content,explanation,order_index) SELECT id,N'The manager asked all staff members to submit ______ reports by Friday.',N'Cần tính từ sở hữu “their” đứng trước danh từ “reports”.',1 FROM quizzes WHERE title=N'TOEIC Mini Mock Test (Part 5 Focus)';

-- QUESTION OPTIONS
IF NOT EXISTS (SELECT 1 FROM question_options o JOIN questions q ON q.id=o.question_id WHERE q.content=N'Mẫu câu nào sau đây phù hợp nhất để mở đầu một email trang trọng gửi đối tác?') INSERT INTO question_options(question_id,content,is_correct) SELECT q.id,v.content,v.correct FROM questions q CROSS APPLY (VALUES (N'Hey Mr. Smith, what''s up?',0),(N'Dear Mr. Smith, I hope this email finds you well.',1),(N'Yo, check this out.',0),(N'Hi friend, write me back asap.',0)) v(content,correct) WHERE q.content=N'Mẫu câu nào sau đây phù hợp nhất để mở đầu một email trang trọng gửi đối tác?';
IF NOT EXISTS (SELECT 1 FROM question_options o JOIN questions q ON q.id=o.question_id WHERE q.content=N'Khi muốn xin phép ngắt lời ai đó một cách lịch sự trong cuộc họp, bạn nên nói gì?') INSERT INTO question_options(question_id,content,is_correct) SELECT q.id,v.content,v.correct FROM questions q CROSS APPLY (VALUES (N'Stop talking now!',0),(N'Listen to me first.',0),(N'May I interrupt for a moment?',1),(N'Shut up please.',0)) v(content,correct) WHERE q.content=N'Khi muốn xin phép ngắt lời ai đó một cách lịch sự trong cuộc họp, bạn nên nói gì?';
IF NOT EXISTS (SELECT 1 FROM question_options o JOIN questions q ON q.id=o.question_id WHERE q.content=N'Từ nào đồng nghĩa với "Postpone a meeting"?') INSERT INTO question_options(question_id,content,is_correct) SELECT q.id,v.content,v.correct FROM questions q CROSS APPLY (VALUES (N'Put off',1),(N'Call off',0),(N'Carry on',0),(N'Bring about',0)) v(content,correct) WHERE q.content=N'Từ nào đồng nghĩa với "Postpone a meeting"?';
IF NOT EXISTS (SELECT 1 FROM question_options o JOIN questions q ON q.id=o.question_id WHERE q.content=N'Trong IELTS Reading, kỹ thuật "Scanning" dùng để làm gì?') INSERT INTO question_options(question_id,content,is_correct) SELECT q.id,v.content,v.correct FROM questions q CROSS APPLY (VALUES (N'Đọc hiểu ý chính toàn bài',0),(N'Tìm thông tin chi tiết cụ thể',1),(N'Dịch từng từ sang tiếng Việt',0),(N'Đoán nghĩa của tiêu đề',0)) v(content,correct) WHERE q.content=N'Trong IELTS Reading, kỹ thuật "Scanning" dùng để làm gì?';
IF NOT EXISTS (SELECT 1 FROM question_options o JOIN questions q ON q.id=o.question_id WHERE q.content=N'Một bài Writing Task 2 tiêu chuẩn nên có tối thiểu bao nhiêu từ?') INSERT INTO question_options(question_id,content,is_correct) SELECT q.id,v.content,v.correct FROM questions q CROSS APPLY (VALUES (N'150 từ',0),(N'200 từ',0),(N'250 từ',1),(N'350 từ',0)) v(content,correct) WHERE q.content=N'Một bài Writing Task 2 tiêu chuẩn nên có tối thiểu bao nhiêu từ?';
IF NOT EXISTS (SELECT 1 FROM question_options o JOIN questions q ON q.id=o.question_id WHERE q.content=N'The manager asked all staff members to submit ______ reports by Friday.') INSERT INTO question_options(question_id,content,is_correct) SELECT q.id,v.content,v.correct FROM questions q CROSS APPLY (VALUES (N'they',0),(N'them',0),(N'their',1),(N'theirs',0)) v(content,correct) WHERE q.content=N'The manager asked all staff members to submit ______ reports by Friday.';

-- COMPLETED ORDERS
IF NOT EXISTS (SELECT 1 FROM orders WHERE order_code='DEMO-001') INSERT INTO orders(order_code,student_id,course_id,amount,payment_method,status,transaction_no,created_at,completed_at) SELECT 'DEMO-001',u.id,c.id,499000,'VNPAY','COMPLETED','DEMO-TXN-001',DATEADD(day,-12,SYSDATETIME()),DATEADD(day,-12,SYSDATETIME()) FROM users u CROSS JOIN courses c WHERE u.email='student@gmail.com' AND c.title=N'Tiếng Anh Giao Tiếp Thực Chiến Cho Người Đi Làm' AND NOT EXISTS (SELECT 1 FROM orders o WHERE o.student_id=u.id AND o.course_id=c.id AND o.status='COMPLETED');
IF NOT EXISTS (SELECT 1 FROM orders WHERE order_code='DEMO-002') INSERT INTO orders(order_code,student_id,course_id,amount,payment_method,status,transaction_no,created_at,completed_at) SELECT 'DEMO-002',u.id,c.id,890000,'MOMO','COMPLETED','DEMO-TXN-002',DATEADD(day,-10,SYSDATETIME()),DATEADD(day,-10,SYSDATETIME()) FROM users u CROSS JOIN courses c WHERE u.email='student@gmail.com' AND c.title=N'Chinh Phục IELTS 7.0+ Toàn Diện 4 Kỹ Năng' AND NOT EXISTS (SELECT 1 FROM orders o WHERE o.student_id=u.id AND o.course_id=c.id AND o.status='COMPLETED');
IF NOT EXISTS (SELECT 1 FROM orders WHERE order_code='DEMO-003') INSERT INTO orders(order_code,student_id,course_id,amount,payment_method,status,transaction_no,created_at,completed_at) SELECT 'DEMO-003',u.id,c.id,499000,'BANK_TRANSFER','COMPLETED','DEMO-TXN-003',DATEADD(day,-8,SYSDATETIME()),DATEADD(day,-8,SYSDATETIME()) FROM users u CROSS JOIN courses c WHERE u.email='student2@gmail.com' AND c.title=N'Tiếng Anh Giao Tiếp Thực Chiến Cho Người Đi Làm' AND NOT EXISTS (SELECT 1 FROM orders o WHERE o.student_id=u.id AND o.course_id=c.id AND o.status='COMPLETED');
IF NOT EXISTS (SELECT 1 FROM orders WHERE order_code='DEMO-004') INSERT INTO orders(order_code,student_id,course_id,amount,payment_method,status,transaction_no,created_at,completed_at) SELECT 'DEMO-004',u.id,c.id,890000,'VNPAY','COMPLETED','DEMO-TXN-004',DATEADD(day,-6,SYSDATETIME()),DATEADD(day,-6,SYSDATETIME()) FROM users u CROSS JOIN courses c WHERE u.email='student2@gmail.com' AND c.title=N'Chinh Phục IELTS 7.0+ Toàn Diện 4 Kỹ Năng' AND NOT EXISTS (SELECT 1 FROM orders o WHERE o.student_id=u.id AND o.course_id=c.id AND o.status='COMPLETED');
IF NOT EXISTS (SELECT 1 FROM orders WHERE order_code='DEMO-005') INSERT INTO orders(order_code,student_id,course_id,amount,payment_method,status,transaction_no,created_at,completed_at) SELECT 'DEMO-005',u.id,c.id,350000,'MOMO','COMPLETED','DEMO-TXN-005',DATEADD(day,-5,SYSDATETIME()),DATEADD(day,-5,SYSDATETIME()) FROM users u CROSS JOIN courses c WHERE u.email='student2@gmail.com' AND c.title=N'Bứt Phá TOEIC 750+ Cấp Tốc Trong 30 Ngày' AND NOT EXISTS (SELECT 1 FROM orders o WHERE o.student_id=u.id AND o.course_id=c.id AND o.status='COMPLETED');
IF NOT EXISTS (SELECT 1 FROM orders WHERE order_code='DEMO-006') INSERT INTO orders(order_code,student_id,course_id,amount,payment_method,status,transaction_no,created_at,completed_at) SELECT 'DEMO-006',u.id,c.id,499000,'VNPAY','COMPLETED','DEMO-TXN-006',DATEADD(day,-7,SYSDATETIME()),DATEADD(day,-7,SYSDATETIME()) FROM users u CROSS JOIN courses c WHERE u.email='student3@gmail.com' AND c.title=N'Tiếng Anh Giao Tiếp Thực Chiến Cho Người Đi Làm' AND NOT EXISTS (SELECT 1 FROM orders o WHERE o.student_id=u.id AND o.course_id=c.id AND o.status='COMPLETED');
IF NOT EXISTS (SELECT 1 FROM orders WHERE order_code='DEMO-007') INSERT INTO orders(order_code,student_id,course_id,amount,payment_method,status,transaction_no,created_at,completed_at) SELECT 'DEMO-007',u.id,c.id,350000,'BANK_TRANSFER','COMPLETED','DEMO-TXN-007',DATEADD(day,-4,SYSDATETIME()),DATEADD(day,-4,SYSDATETIME()) FROM users u CROSS JOIN courses c WHERE u.email='student3@gmail.com' AND c.title=N'Bứt Phá TOEIC 750+ Cấp Tốc Trong 30 Ngày' AND NOT EXISTS (SELECT 1 FROM orders o WHERE o.student_id=u.id AND o.course_id=c.id AND o.status='COMPLETED');
IF NOT EXISTS (SELECT 1 FROM orders WHERE order_code='DEMO-008') INSERT INTO orders(order_code,student_id,course_id,amount,payment_method,status,transaction_no,created_at,completed_at) SELECT 'DEMO-008',u.id,c.id,550000,'MOMO','COMPLETED','DEMO-TXN-008',DATEADD(day,-2,SYSDATETIME()),DATEADD(day,-2,SYSDATETIME()) FROM users u CROSS JOIN courses c WHERE u.email='student3@gmail.com' AND c.title=N'Tiếng Anh Chuyên Ngành CNTT (IT English)' AND NOT EXISTS (SELECT 1 FROM orders o WHERE o.student_id=u.id AND o.course_id=c.id AND o.status='COMPLETED');
IF NOT EXISTS (SELECT 1 FROM orders WHERE order_code='DEMO-009') INSERT INTO orders(order_code,student_id,course_id,amount,payment_method,status,transaction_no,created_at,completed_at) SELECT 'DEMO-009',u.id,c.id,890000,'VNPAY','COMPLETED','DEMO-TXN-009',DATEADD(day,-9,SYSDATETIME()),DATEADD(day,-9,SYSDATETIME()) FROM users u CROSS JOIN courses c WHERE u.email='student4@gmail.com' AND c.title=N'Chinh Phục IELTS 7.0+ Toàn Diện 4 Kỹ Năng' AND NOT EXISTS (SELECT 1 FROM orders o WHERE o.student_id=u.id AND o.course_id=c.id AND o.status='COMPLETED');
IF NOT EXISTS (SELECT 1 FROM orders WHERE order_code='DEMO-010') INSERT INTO orders(order_code,student_id,course_id,amount,payment_method,status,transaction_no,created_at,completed_at) SELECT 'DEMO-010',u.id,c.id,550000,'MOMO','COMPLETED','DEMO-TXN-010',DATEADD(day,-3,SYSDATETIME()),DATEADD(day,-3,SYSDATETIME()) FROM users u CROSS JOIN courses c WHERE u.email='student4@gmail.com' AND c.title=N'Tiếng Anh Chuyên Ngành CNTT (IT English)' AND NOT EXISTS (SELECT 1 FROM orders o WHERE o.student_id=u.id AND o.course_id=c.id AND o.status='COMPLETED');
IF NOT EXISTS (SELECT 1 FROM orders WHERE order_code='DEMO-011') INSERT INTO orders(order_code,student_id,course_id,amount,payment_method,status,transaction_no,created_at,completed_at) SELECT 'DEMO-011',u.id,c.id,299000,'BANK_TRANSFER','COMPLETED','DEMO-TXN-011',DATEADD(day,-1,SYSDATETIME()),DATEADD(day,-1,SYSDATETIME()) FROM users u CROSS JOIN courses c WHERE u.email='student4@gmail.com' AND c.title=N'Ngữ Pháp Tiếng Anh Nền Tảng A-Z' AND NOT EXISTS (SELECT 1 FROM orders o WHERE o.student_id=u.id AND o.course_id=c.id AND o.status='COMPLETED');
IF NOT EXISTS (SELECT 1 FROM orders WHERE order_code='DEMO-012') INSERT INTO orders(order_code,student_id,course_id,amount,payment_method,status,transaction_no,created_at,completed_at) SELECT 'DEMO-012',u.id,c.id,499000,'VNPAY','COMPLETED','DEMO-TXN-012',DATEADD(day,-11,SYSDATETIME()),DATEADD(day,-11,SYSDATETIME()) FROM users u CROSS JOIN courses c WHERE u.email='student5@gmail.com' AND c.title=N'Tiếng Anh Giao Tiếp Thực Chiến Cho Người Đi Làm' AND NOT EXISTS (SELECT 1 FROM orders o WHERE o.student_id=u.id AND o.course_id=c.id AND o.status='COMPLETED');
IF NOT EXISTS (SELECT 1 FROM orders WHERE order_code='DEMO-013') INSERT INTO orders(order_code,student_id,course_id,amount,payment_method,status,transaction_no,created_at,completed_at) SELECT 'DEMO-013',u.id,c.id,350000,'MOMO','COMPLETED','DEMO-TXN-013',DATEADD(day,-6,SYSDATETIME()),DATEADD(day,-6,SYSDATETIME()) FROM users u CROSS JOIN courses c WHERE u.email='student5@gmail.com' AND c.title=N'Bứt Phá TOEIC 750+ Cấp Tốc Trong 30 Ngày' AND NOT EXISTS (SELECT 1 FROM orders o WHERE o.student_id=u.id AND o.course_id=c.id AND o.status='COMPLETED');
IF NOT EXISTS (SELECT 1 FROM orders WHERE order_code='DEMO-014') INSERT INTO orders(order_code,student_id,course_id,amount,payment_method,status,transaction_no,created_at,completed_at) SELECT 'DEMO-014',u.id,c.id,299000,'BANK_TRANSFER','COMPLETED','DEMO-TXN-014',DATEADD(day,-2,SYSDATETIME()),DATEADD(day,-2,SYSDATETIME()) FROM users u CROSS JOIN courses c WHERE u.email='student5@gmail.com' AND c.title=N'Ngữ Pháp Tiếng Anh Nền Tảng A-Z' AND NOT EXISTS (SELECT 1 FROM orders o WHERE o.student_id=u.id AND o.course_id=c.id AND o.status='COMPLETED');

-- ENROLLMENTS are derived from successful demo orders
INSERT INTO enrollments(student_id,course_id) SELECT DISTINCT o.student_id,o.course_id FROM orders o WHERE o.status='COMPLETED' AND NOT EXISTS (SELECT 1 FROM enrollments e WHERE e.student_id=o.student_id AND e.course_id=o.course_id);

-- LESSON PROGRESS
INSERT INTO lesson_progress(student_id,lesson_id,is_completed) SELECT u.id,l.id,1 FROM users u CROSS JOIN lessons l WHERE u.email='student@gmail.com' AND l.title IN (N'Bài 1: Tự tin giới thiệu bản thân & công việc',N'Bài 2: Viết Email và tin nhắn công việc chuyên nghiệp',N'Bài 3: Đặt lịch họp và xác nhận qua điện thoại',N'Bài 4: Mẫu câu đưa ra ý kiến trong cuộc họp',N'Bài 5: Kỹ năng thuyết trình dự án bằng tiếng Anh') AND NOT EXISTS (SELECT 1 FROM lesson_progress p WHERE p.student_id=u.id AND p.lesson_id=l.id);
INSERT INTO lesson_progress(student_id,lesson_id,is_completed) SELECT u.id,l.id,CASE WHEN l.title=N'Bài 3: Cấu trúc bài luận Writing Task 2' THEN 0 ELSE 1 END FROM users u CROSS JOIN lessons l WHERE u.email='student@gmail.com' AND l.title IN (N'Bài 1: Phương pháp xử lý Multiple Choice trong Listening',N'Bài 2: Chiến lược Skimming & Scanning trong Reading',N'Bài 3: Cấu trúc bài luận Writing Task 2') AND NOT EXISTS (SELECT 1 FROM lesson_progress p WHERE p.student_id=u.id AND p.lesson_id=l.id);
INSERT INTO lesson_progress(student_id,lesson_id,is_completed) SELECT u.id,l.id,1 FROM users u CROSS JOIN lessons l WHERE u.email='student2@gmail.com' AND l.title IN (N'Bài 1: Tự tin giới thiệu bản thân & công việc',N'Bài 2: Viết Email và tin nhắn công việc chuyên nghiệp',N'Bài 3: Đặt lịch họp và xác nhận qua điện thoại') AND NOT EXISTS (SELECT 1 FROM lesson_progress p WHERE p.student_id=u.id AND p.lesson_id=l.id);
INSERT INTO lesson_progress(student_id,lesson_id,is_completed) SELECT u.id,l.id,1 FROM users u CROSS JOIN lessons l WHERE u.email='student2@gmail.com' AND l.title IN (N'Bài 1: Dạng câu hỏi về Từ loại',N'Bài 2: Bẫy Mệnh đề quan hệ') AND NOT EXISTS (SELECT 1 FROM lesson_progress p WHERE p.student_id=u.id AND p.lesson_id=l.id);
INSERT INTO lesson_progress(student_id,lesson_id,is_completed) SELECT u.id,l.id,1 FROM users u CROSS JOIN lessons l WHERE u.email='student3@gmail.com' AND l.title IN (N'Bài 1: Tự tin giới thiệu bản thân & công việc',N'Bài 2: Viết Email và tin nhắn công việc chuyên nghiệp') AND NOT EXISTS (SELECT 1 FROM lesson_progress p WHERE p.student_id=u.id AND p.lesson_id=l.id);
INSERT INTO lesson_progress(student_id,lesson_id,is_completed) SELECT u.id,l.id,1 FROM users u CROSS JOIN lessons l WHERE u.email='student3@gmail.com' AND l.title IN (N'Bài 1: Báo cáo tiến độ Daily Standup Meeting',N'Bài 2: Đọc hiểu API Specs & Git Workflow') AND NOT EXISTS (SELECT 1 FROM lesson_progress p WHERE p.student_id=u.id AND p.lesson_id=l.id);
INSERT INTO lesson_progress(student_id,lesson_id,is_completed) SELECT u.id,l.id,1 FROM users u CROSS JOIN lessons l WHERE u.email='student4@gmail.com' AND l.title IN (N'Bài 1: Phương pháp xử lý Multiple Choice trong Listening',N'Bài 2: Chiến lược Skimming & Scanning trong Reading',N'Bài 3: Cấu trúc bài luận Writing Task 2',N'Bài 4: Bứt phá Speaking Part 2 và 3') AND NOT EXISTS (SELECT 1 FROM lesson_progress p WHERE p.student_id=u.id AND p.lesson_id=l.id);
INSERT INTO lesson_progress(student_id,lesson_id,is_completed) SELECT u.id,l.id,1 FROM users u CROSS JOIN lessons l WHERE u.email='student4@gmail.com' AND l.title=N'Bài 1: Hiện tại đơn & Tiếp diễn' AND NOT EXISTS (SELECT 1 FROM lesson_progress p WHERE p.student_id=u.id AND p.lesson_id=l.id);
INSERT INTO lesson_progress(student_id,lesson_id,is_completed) SELECT u.id,l.id,1 FROM users u CROSS JOIN lessons l WHERE u.email='student5@gmail.com' AND l.title=N'Bài 1: Tự tin giới thiệu bản thân & công việc' AND NOT EXISTS (SELECT 1 FROM lesson_progress p WHERE p.student_id=u.id AND p.lesson_id=l.id);
INSERT INTO lesson_progress(student_id,lesson_id,is_completed) SELECT u.id,l.id,1 FROM users u CROSS JOIN lessons l WHERE u.email='student5@gmail.com' AND l.title IN (N'Bài 1: Hiện tại đơn & Tiếp diễn',N'Bài 2: Quá khứ đơn & Hoàn thành') AND NOT EXISTS (SELECT 1 FROM lesson_progress p WHERE p.student_id=u.id AND p.lesson_id=l.id);

-- QUIZ RESULTS
IF NOT EXISTS (SELECT 1 FROM quiz_results r JOIN users u ON u.id=r.student_id JOIN quizzes q ON q.id=r.quiz_id WHERE u.email='student@gmail.com' AND q.title=N'Kiểm tra Đánh giá Giao tiếp Công sở (Quiz 1)') INSERT INTO quiz_results(student_id,quiz_id,score,correct_count,total_questions,passed,started_at,submitted_at) SELECT u.id,q.id,100,3,3,1,DATEADD(minute,-12,DATEADD(day,-10,SYSDATETIME())),DATEADD(day,-10,SYSDATETIME()) FROM users u CROSS JOIN quizzes q WHERE u.email='student@gmail.com' AND q.title=N'Kiểm tra Đánh giá Giao tiếp Công sở (Quiz 1)';
IF NOT EXISTS (SELECT 1 FROM quiz_results r JOIN users u ON u.id=r.student_id JOIN quizzes q ON q.id=r.quiz_id WHERE u.email='student@gmail.com' AND q.title=N'IELTS Diagnostic Assessment (Band 7.0 Test)') INSERT INTO quiz_results(student_id,quiz_id,score,correct_count,total_questions,passed,started_at,submitted_at) SELECT u.id,q.id,85,2,2,1,DATEADD(minute,-18,DATEADD(day,-8,SYSDATETIME())),DATEADD(day,-8,SYSDATETIME()) FROM users u CROSS JOIN quizzes q WHERE u.email='student@gmail.com' AND q.title=N'IELTS Diagnostic Assessment (Band 7.0 Test)';
IF NOT EXISTS (SELECT 1 FROM quiz_results r JOIN users u ON u.id=r.student_id JOIN quizzes q ON q.id=r.quiz_id WHERE u.email='student2@gmail.com' AND q.title=N'Kiểm tra Đánh giá Giao tiếp Công sở (Quiz 1)') INSERT INTO quiz_results(student_id,quiz_id,score,correct_count,total_questions,passed,started_at,submitted_at) SELECT u.id,q.id,66.7,2,3,0,DATEADD(minute,-14,DATEADD(day,-5,SYSDATETIME())),DATEADD(day,-5,SYSDATETIME()) FROM users u CROSS JOIN quizzes q WHERE u.email='student2@gmail.com' AND q.title=N'Kiểm tra Đánh giá Giao tiếp Công sở (Quiz 1)';
IF NOT EXISTS (SELECT 1 FROM quiz_results r JOIN users u ON u.id=r.student_id JOIN quizzes q ON q.id=r.quiz_id WHERE u.email='student2@gmail.com' AND q.title=N'TOEIC Mini Mock Test (Part 5 Focus)') INSERT INTO quiz_results(student_id,quiz_id,score,correct_count,total_questions,passed,started_at,submitted_at) SELECT u.id,q.id,100,1,1,1,DATEADD(minute,-8,DATEADD(day,-4,SYSDATETIME())),DATEADD(day,-4,SYSDATETIME()) FROM users u CROSS JOIN quizzes q WHERE u.email='student2@gmail.com' AND q.title=N'TOEIC Mini Mock Test (Part 5 Focus)';
IF NOT EXISTS (SELECT 1 FROM quiz_results r JOIN users u ON u.id=r.student_id JOIN quizzes q ON q.id=r.quiz_id WHERE u.email='student3@gmail.com' AND q.title=N'Kiểm tra Đánh giá Giao tiếp Công sở (Quiz 1)') INSERT INTO quiz_results(student_id,quiz_id,score,correct_count,total_questions,passed,started_at,submitted_at) SELECT u.id,q.id,100,3,3,1,DATEADD(minute,-11,DATEADD(day,-3,SYSDATETIME())),DATEADD(day,-3,SYSDATETIME()) FROM users u CROSS JOIN quizzes q WHERE u.email='student3@gmail.com' AND q.title=N'Kiểm tra Đánh giá Giao tiếp Công sở (Quiz 1)';
IF NOT EXISTS (SELECT 1 FROM quiz_results r JOIN users u ON u.id=r.student_id JOIN quizzes q ON q.id=r.quiz_id WHERE u.email='student4@gmail.com' AND q.title=N'IELTS Diagnostic Assessment (Band 7.0 Test)') INSERT INTO quiz_results(student_id,quiz_id,score,correct_count,total_questions,passed,started_at,submitted_at) SELECT u.id,q.id,90,2,2,1,DATEADD(minute,-17,DATEADD(day,-2,SYSDATETIME())),DATEADD(day,-2,SYSDATETIME()) FROM users u CROSS JOIN quizzes q WHERE u.email='student4@gmail.com' AND q.title=N'IELTS Diagnostic Assessment (Band 7.0 Test)';
IF NOT EXISTS (SELECT 1 FROM quiz_results r JOIN users u ON u.id=r.student_id JOIN quizzes q ON q.id=r.quiz_id WHERE u.email='student5@gmail.com' AND q.title=N'Kiểm tra Đánh giá Giao tiếp Công sở (Quiz 1)') INSERT INTO quiz_results(student_id,quiz_id,score,correct_count,total_questions,passed,started_at,submitted_at) SELECT u.id,q.id,100,3,3,1,DATEADD(minute,-10,DATEADD(day,-1,SYSDATETIME())),DATEADD(day,-1,SYSDATETIME()) FROM users u CROSS JOIN quizzes q WHERE u.email='student5@gmail.com' AND q.title=N'Kiểm tra Đánh giá Giao tiếp Công sở (Quiz 1)';
